version: '3.9'

services:
  backend:
    build: ./backend/
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - nss_network
  react-app:
    build: ./front_nss
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nss_network

networks:
  nss_network:
    driver: bridge
