"""fixes user created at

Revision ID: 47b71656a6a9
Revises: 9509d05ca775
Create Date: 2024-11-23 21:41:36.392157

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47b71656a6a9"
down_revision = "9509d05ca775"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_at", sa.DateTime(), nullable=True)
        )
        batch_op.drop_column("creted_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("creted_at", sa.DATETIME(), nullable=True)
        )
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
