"""altered User

Revision ID: 9509d05ca775
Revises:
Create Date: 2024-11-23 21:06:46.360372

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9509d05ca775"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("first_name", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("second_name", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("creted_at", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_login", sa.DateTime(), nullable=True)
        )
        batch_op.create_unique_constraint("uq_user_email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("last_login")
        batch_op.drop_column("creted_at")
        batch_op.drop_column("second_name")
        batch_op.drop_column("first_name")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
